In [1]:
sql_fact = pd.read_csv("sql fact file.csv")

NameError: name 'pd' is not defined

In [2]:
import pandas as pd

df = pd.read_csv("sql fact file.csv")

print(df.shape)
print(df.columns.tolist())

(20000, 21)
['TripID', 'RouteKey', 'BusKey', 'TimeKey', 'PerfKey', 'StartTime', 'EndTime', 'FuelConsumed', 'Distance', 'TargetTime', 'ActualTime', 'DelayAnalysis', 'OperatingCostPerKM', 'PassengerCount', 'EngineTemperature', 'RPM', 'FuelRate', 'IdleDuration', 'AverageSpeed', 'BrakeEvents', 'OTPFlag']

In [3]:
print('AverageSpeed' in df.columns)

True

In [4]:
df['AverageSpeed'].describe()

count    20000.000000
mean        42.449628
std         15.864767
min         15.000000
25%         28.767500
50%         42.295000
75%         56.250000
max         69.990000
Name: AverageSpeed, dtype: float64

In [5]:
print('AverageSpeed' in df.columns)

True

In [6]:
df['IdleRatio'] = df['IdleDuration'] / df['ActualTime']

df[['IdleDuration','ActualTime','IdleRatio']].head()

   IdleDuration  ActualTime  IdleRatio
0            31         170   0.182353
1            14         145   0.096552
2            21          61   0.344262
3             7         168   0.041667
4            36         110   0.327273

In [7]:
df['IdleRatio'].describe()

count    20000.000000
mean         0.213391
std          0.181727
min          0.004255
25%          0.089286
50%          0.175115
75%          0.278846
max          2.142857
Name: IdleRatio, dtype: float64

In [8]:
high_idle = df[df['IdleRatio'] > 1]

print("Rows with IdleRatio > 1:", len(high_idle))

Rows with IdleRatio > 1: 124

In [9]:
high_idle[['IdleDuration','ActualTime','IdleRatio']].head()

     IdleDuration  ActualTime  IdleRatio
533            35          31   1.129032
746            38          28   1.357143
867            35          25   1.400000
893            40          34   1.176471
954            44          43   1.023256

In [10]:
df.to_csv(
    "Feature_Engineered_Transit_Data.csv",
    index=False
)

print("Feature Engineering Completed")

Feature Engineering Completed

In [11]:
from sklearn.preprocessing import StandardScaler

In [18]:
scaled_df = df.copy()

In [19]:
fuel_cols = [
    'FuelConsumed',
    'FuelEfficiency',
    'FuelPerKM'
]

In [20]:
scaler = StandardScaler()

scaled_df[fuel_cols] = scaler.fit_transform(
    scaled_df[fuel_cols]
)

KeyError: "['FuelEfficiency', 'FuelPerKM'] not in index"

In [21]:
# Create fuel-related variables if they are missing

if 'FuelEfficiency' not in df.columns:
    df['FuelEfficiency'] = df['Distance'] / df['FuelConsumed']

if 'FuelPerKM' not in df.columns:
    df['FuelPerKM'] = df['FuelConsumed'] / df['Distance']

print(df[['FuelConsumed', 'FuelEfficiency', 'FuelPerKM']].head())

   FuelConsumed  FuelEfficiency  FuelPerKM
0          5.91        2.223350   0.449772
1          2.38        2.231092   0.448211
2         19.65        2.958270   0.338035
3         17.25        4.198841   0.238161
4          2.31       24.181818   0.041353

In [22]:
from sklearn.preprocessing import StandardScaler

scaled_df = df.copy()

fuel_cols = ['FuelConsumed', 'FuelEfficiency', 'FuelPerKM']

scaler = StandardScaler()

scaled_df[fuel_cols] = scaler.fit_transform(scaled_df[fuel_cols])

print(scaled_df[fuel_cols].head())

   FuelConsumed  FuelEfficiency  FuelPerKM
0     -0.829370       -0.544089   0.139508
1     -1.470844       -0.543154   0.136015
2      1.667470       -0.455276  -0.110574
3      1.231341       -0.305355  -0.334108
4     -1.483564        2.109546  -0.774593

In [23]:
scaled_df.to_csv("Standardized_Transit_Data.csv", index=False)

print("Standardization Completed")

Standardization Completed

# Day 14 – Feature Engineering and Data Preparation

## Objective
Prepare transit operational data for future machine learning models.

## Tasks Performed

### Feature Engineering
- Validated AverageSpeed feature.
- Created IdleRatio using IdleDuration and ActualTime.
- Created FuelEfficiency feature.
- Created FuelPerKM feature.

### Data Preparation
- Applied StandardScaler to:
  - FuelConsumed
  - FuelEfficiency
  - FuelPerKM

### Observations
- Most IdleRatio values were below 1.
- Some records had IdleRatio > 1, indicating operational anomalies.
- Standardization transformed fuel variables to a common scale suitable for machine learning algorithms.

## Outcome
The dataset is now ready for feature selection and machine learning model development.

In [24]:
print('AverageSpeed' in df.columns)
print(df['AverageSpeed'].head())
print(df['AverageSpeed'].describe())

True
0    17.62
1    39.57
2    54.85
3    36.38
4    38.23
Name: AverageSpeed, dtype: float64
count    20000.000000
mean        42.449628
std         15.864767
min         15.000000
25%         28.767500
50%         42.295000
75%         56.250000
max         69.990000
Name: AverageSpeed, dtype: float64

In [25]:
print('IdleRatio' in df.columns)
print(df['IdleRatio'].head())
print(df['IdleRatio'].describe())

True
0    0.182353
1    0.096552
2    0.344262
3    0.041667
4    0.327273
Name: IdleRatio, dtype: float64
count    20000.000000
mean         0.213391
std          0.181727
min          0.004255
25%          0.089286
50%          0.175115
75%          0.278846
max          2.142857
Name: IdleRatio, dtype: float64

In [26]:
scaled_df[['FuelConsumed',
           'FuelEfficiency',
           'FuelPerKM']].describe()

       FuelConsumed  FuelEfficiency     FuelPerKM
count  20000.000000    2.000000e+04  2.000000e+04
mean       0.000000   -2.323475e-16  1.190159e-17
std        1.000025    1.000025e+00  1.000025e+00
min       -1.721618   -7.807422e-01 -8.383766e-01
25%       -0.876617   -5.393873e-01 -5.645538e-01
50%        0.011996   -3.209916e-01 -3.171604e-01
75%        0.867900    8.107897e-02  1.221951e-01
max        1.731073    8.587982e+00  7.576197e+00

In [27]:
print(df[['FuelConsumed',
          'FuelEfficiency',
          'FuelPerKM']].head())

   FuelConsumed  FuelEfficiency  FuelPerKM
0          5.91        2.223350   0.449772
1          2.38        2.231092   0.448211
2         19.65        2.958270   0.338035
3         17.25        4.198841   0.238161
4          2.31       24.181818   0.041353

In [28]:
import os

print(os.path.exists(
    "Feature_Engineered_Transit_Data.csv"
))

True

In [29]:
import os

print(os.path.exists(
    "Standardized_Transit_Data.csv"
))

True

In [30]:
scaled_df[['FuelConsumed',
           'FuelEfficiency',
           'FuelPerKM']].describe()

       FuelConsumed  FuelEfficiency     FuelPerKM
count  20000.000000    2.000000e+04  2.000000e+04
mean       0.000000   -2.323475e-16  1.190159e-17
std        1.000025    1.000025e+00  1.000025e+00
min       -1.721618   -7.807422e-01 -8.383766e-01
25%       -0.876617   -5.393873e-01 -5.645538e-01
50%        0.011996   -3.209916e-01 -3.171604e-01
75%        0.867900    8.107897e-02  1.221951e-01
max        1.731073    8.587982e+00  7.576197e+00